# Generated by Django 4.2.3 on 2024-04-26 09:20

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotique',
            name='file',
            field=models.FileField(max_length=512, null=True, upload_to=api.models.uoload_document, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx']), django.core.validators.MaxValueValidator(3145728)]),
        ),
    ]
