# Generated by Django 4.2.3 on 2023-11-11 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('useraub_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.useraub',),
        ),
        migrations.AlterField(
            model_name='useraub',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Gerant', 'Gerant'), ('Agent', 'Agent')], default='Gerant', max_length=30, null=True),
        ),
    ]
