# Generated by Django 4.2.3 on 2023-10-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraub',
            name='number_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
