# Generated by Django 4.2.3 on 2023-11-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_alter_useraub_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='agent',
        ),
        migrations.AddField(
            model_name='documents',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
    ]
