# Generated by Django 4.2.3 on 2023-10-31 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useraub_number_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='agent',
        ),
        migrations.AddField(
            model_name='agent',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.direction'),
        ),
    ]
