# Generated by Django 4.2.3 on 2024-04-26 09:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_plotique_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotique',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.uoload_document, validators=[api.models.validate_file_size]),
        ),
    ]
