# Generated by Django 4.2.3 on 2024-04-26 09:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plotique_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.uoload_document, validators=[api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='charts',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.uoload_document, validators=[api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='decision',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.uoload_document, validators=[api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.uoload_document, validators=[api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.uoload_document, validators=[api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='procedur',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.uoload_document, validators=[api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='textgouvernance',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.uoload_document, validators=[api.models.validate_file_size]),
        ),
    ]
