# Generated by Django 4.2.3 on 2023-11-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_documents_agent_documents_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
