# Generated by Django 4.2.3 on 2023-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_documents_date_ajout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('documents', models.ManyToManyField(related_name='archives_in_documents', to='api.documents')),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='archives',
            field=models.ManyToManyField(blank=True, related_name='documents_in_archives', to='api.archive'),
        ),
    ]
