# Generated by Django 4.2.3 on 2024-05-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_useraub_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraub',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
    ]
