# Generated by Django 4.2.3 on 2023-11-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_archive_documents_archives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='documents',
        ),
        migrations.AddField(
            model_name='archive',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='documents',
            name='archives',
        ),
        migrations.AddField(
            model_name='documents',
            name='archives',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.archive'),
        ),
    ]
