# Generated by Django 4.2.3 on 2023-11-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_archive_documents_archive_date_ajout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.archive'),
        ),
        migrations.AddField(
            model_name='agent',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.archive'),
        ),
        migrations.AddField(
            model_name='gerant',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.archive'),
        ),
    ]
