# Generated by Django 4.2.3 on 2023-11-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_admin_archive_agent_archive_gerant_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraub',
            name='username',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
