# Generated by Django 4.2.3 on 2023-12-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_avis_user_avis_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='users',
            new_name='user',
        ),
    ]
