# Generated by Django 4.2.3 on 2023-12-21 13:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_users_avis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.uoload_document),
        ),
    ]
