# Generated by Django 4.2.3 on 2024-01-10 12:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_plotique'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, editable=False, max_length=100, null=True),
        ),
    ]
