# Generated by Django 4.2.3 on 2024-04-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_plotique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraub',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
