# Generated by Django 4.2.3 on 2024-04-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_charts_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.direction'),
        ),
    ]
