# Generated by Django 4.2.3 on 2024-04-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_admin_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='gerant',
            name='archive',
        ),
    ]
